# Generated by Django 3.2.8 on 2021-12-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Team',
        ),
    ]
